# Generated by Django 5.0.7 on 2024-07-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('turi', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('foydalari', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('turi', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('foydalari', models.CharField(max_length=200)),
            ],
        ),
    ]
