# Generated by Django 5.0.7 on 2024-07-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegetables',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fruit',
            name='turi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vegetables',
            name='turi',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
