# Generated by Django 5.0.7 on 2024-07-21 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_fruit_image_vegetables_image_alter_fruit_turi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='fruit',
            name='turi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.turi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vegetables',
            name='turi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.turi'),
            preserve_default=False,
        ),
    ]
