# Generated by Django 5.0.7 on 2024-07-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_turi_alter_fruit_turi_alter_vegetables_turi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turi',
            name='turi',
            field=models.CharField(),
        ),
    ]
