# Generated by Django 5.0.7 on 2025-10-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_bread_meat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='image',
            field=models.ImageField(upload_to='fruit/'),
        ),
    ]
